name: Update GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Move latest database files under lyrics.git
      run: mkdir lyrics.git && mv database lyrics.git

    - name: Clone lyrics-website-generator.git
      run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Lyrics/lyrics-website-generator.git lyrics-website-generator.git

    - name: Clone lyrics.github.io.git
      run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Lyrics/lyrics.github.io.git lyrics.github.io.git

    - name: Generate static website files
      run: cd lyrics-website-generator.git && sudo apt-get install python3-setuptools sassc && pip3 install pystache && make

    - name: Overwrite and deploy website files
      run: |
        cd lyrics.github.io.git
        git config user.email "open.lyrics.database@gmail.com"
        git config user.name "lyrics-admin"
        git remote set-url origin https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/Lyrics/lyrics.github.io.git
        make clean
        mv ../lyrics-website-generator.git/www/* .
        make deploy
